name: CI

on:
  push:
    paths-ignore:
      - '.github/**'

permissions: read-all

jobs:
  test:
    uses: mitlibraries/.github/.github/workflows/python-uv-shared-test.yml@3d2816ffa487f3e99b650103252e44552d277ef6 # main
  lint:
    uses: mitlibraries/.github/.github/workflows/python-uv-shared-lint.yml@3d2816ffa487f3e99b650103252e44552d277ef6 # main
