name: CI

on:
  push:
    paths-ignore:
      - '.github/**'

permissions: read-all

jobs:
  test:
    uses: mitlibraries/.github/.github/workflows/python-uv-shared-test.yml@main
  lint:
    uses: mitlibraries/.github/.github/workflows/python-uv-shared-lint.yml@main
